apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app_name }}
  namespace: argocd
  labels:
    teste: "cenas"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true