apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-topics
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/RuiEusebio/kafka-management.git
      revision: HEAD
      files:
      - path: "topics/**/*.yaml"
  template:
    metadata:
      name: '{{`topic-{{topicName}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/RuiEusebio/topic-management-template.git
        targetRevision: HEAD
        path: .
        helm:
          parameters:
            - name: topic.name
              value: '{{`{{topicName}}`}}'
            - name: topic.partitions
              value: '{{`{{nr_partions}}`}}'
            - name: topic.replicas
              value: '{{`{{replicas}}`}}'
            {{- range $consumer, $i := {{`consumers`}} }}  
            - name: consumers[{{$i}}]
              value: '{{`{{consumers[$i]}}`}}'
            {{- end }}  
      destination:
        server: https://kubernetes.default.svc
        namespace: confluent
      syncPolicy:
        automated:
          prune: true
          selfHeal: true     